### ISSUE TITLE
Need to dynamically install the latest ruby version

### ISSUE THREAD

**Issue by neilh** [platform45/let-there-be-light#1]
no idea how to get the latest stable build of ruby from the command line.

**Comment by jc1arke** [comment]
``` ruby
#!/usr/bin/env ruby
puts `~/.rbenv/bin/rbenv install --list`.split("\n").map{|item| item.strip}.select{|item| item[/^\d*\.\d*\.\d*/]}.reject{|item| (item.include? '-') && !(item =~ /-p\d*$/)}.last
```

That will consistently get the latest stable version for you :)
Will have a look at how to do this in pure shell scripting terms once I am home tonight

**Comment by neilh** [comment]
awesome!

**Comment by wiehann** [comment]
Pull request here: https://github.com/platform45/let-there-be-light/pull/2
